### ISSUE TITLE
Homework Feedback - JS2- week6

### ISSUE THREAD

**Issue by Swapna-Sahu** [SinaNBA/hyf-homework#1]
WARM UP exercise and Homework both looks perfect 🥇 
Very Nice work on DOM . Everything works fine. 

I have only two comments for warm up
Task 1 &2 - Can you use filter and submit again
Task 3 - Filter also work as forEach so you do not need to write forEach. Please modify.

Keep working on code. 👍

**Comment by SinaNBA** [comment]
thanks a lot for the feedback. when I have done it (Task 1,2,3) I will let you know 👍
