### ISSUE TITLE
Homework Feedback - JS2-week5

### ISSUE THREAD

**Issue by Swapna-Sahu** [SinaNBA/hyf-homework#2]
Very Well done 🥇 . I liked the Fastest presser game. Coding is very short and readable.

Also good work in warm up exercise. I think you forgot to do one task here : 
Create a function (outer) that returns a function (inner). Call the outer function and assign the return to a variable. Now call this variable (that is the inner function) 

Everything look perfect. Impressive work 👍

**Comment by SinaNBA** [comment]
thank you so much Swapna-Sahu for your feedback it was really ecouraging. I'll do that 👍
